### ISSUE TITLE
Power usage calculation not working

### ISSUE THREAD

**Issue by kflinderman** [kflinderman/Hassio#16]
It's not calculating sensor.watthour or anything like that.

```
[homeassistant.components.python_script.watthour.py] Error executing script: float() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 196, in execute
    exec(compiled.code, restricted_globals)
  File "watthour.py", line 23, in <module>
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by kflinderman** [comment]
Looks fixed 25ff0e3cd27f4e73984036fbe9dda66f78984226
