### ISSUE TITLE
Something Wrong with Zwave

### ISSUE THREAD

**Issue by kflinderman** [kflinderman/Hassio#24]
```
ERROR (Dummy-3) [openzwave] Error in manager callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/openzwave/network.py", line 982, in zwcallback
    self._handle_notification(args)
  File "/usr/local/lib/python3.7/site-packages/openzwave/network.py", line 1576, in _handle_notification
    **{'network': self, 'args': args})
  File "/usr/local/lib/python3.7/site-packages/pydispatch/dispatcher.py", line 338, in send
    **named
  File "/usr/local/lib/python3.7/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/src/homeassistant/homeassistant/components/zwave/node_entity.py", line 201, in network_node_changed
    self.node_changed()
  File "/usr/src/homeassistant/homeassistant/components/zwave/node_entity.py", line 243, in node_changed
    self.maybe_schedule_update()
  File "/usr/src/homeassistant/homeassistant/components/zwave/node_entity.py", line 79, in maybe_schedule_update
    self.hass.add_job(self._schedule_update)
  File "/usr/src/homeassistant/homeassistant/core.py", line 279, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 732, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by kflinderman** [comment]
Duplicate of #27 

Not a zwave problem, I think it's a lightpack problem
